### ISSUE TITLE
Levantar os parâmetros de funcionamento do circuito

### ISSUE THREAD

**Issue by tfvieira** [lucasmmassa/acoustic_levitator#1]

**Comment by lucasmmassa** [comment]
### Parâmetros mensurados:
**Tensão 6V:** corrente de 310mA.
**Tensão 7V:** corrente de 370mA.
**Tensão 8V:** corrente de 420mA.
**Tensão 12V:** corrente de 630 mA.

**Comment by lucasmmassa** [comment]
Link para o projeto original: [https://www.instructables.com/Acoustic-Levitator/](url)
